### ISSUE TITLE
Link to my Pokemonlist

### ISSUE THREAD

**Issue by Cantfirmed** [htl-perg-2018-19-4ahif/angular-routing-example-Cantfirmed#1]
https://silly-visvesvaraya-cd793f.netlify.com/pokemon

**Comment by rstropek** [comment]
Hi @Cantfirmed!

Nice, works as expected. The extra point is yours. BTW: If you want to get rid of error when refreshing page (F5), checkout [this function of Netlify](https://www.netlify.com/docs/redirects/#custom-404).

Greetings,
Rainer Stropek.
